name: CI Monorepo

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [backend]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: ESLint & Prettier
        run: yarn lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [backend]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate App Key
        run: echo "APP_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV
      - name: Generate db for test
        run: |
          mkdir -p tmp
          touch /tmp/db.sqlite3
#          yarn node ace migration:run

      - name: Run tests
        env:
          TZ: UTC
          PORT: 3333
          HOST: localhost
          LOG_LEVEL: info
          APP_KEY: ${{ env.APP_KEY }}
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: user
          DB_PASSWORD: password
          DB_DATABASE: hbmanager_test
          DATABASE_URL: postgres://user:password@localhost:5432/hbmanager_test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: secret
          JWT_EXPIRES_IN: 1H
        run: yarn test

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [backend]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.6.0 --activate
