
name: CI Monorepo

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [backend]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: ESLint & Prettier
        run: yarn lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [backend]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.6.0 --activate

      - name:  Install dependencies
        run: yarn install --immutable

      - name: Run tests
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/hbmanager_test
          REDIS_URL: redis://localhost:6379
        run: yarn test

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [backend]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@4.6.0 --activate
